name = "myvard"
main = "src/worker.js"
compatibility_date = "2026-05-21"
workers_dev = true
preview_urls = false

[assets]
directory = "public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
APP_BASE_URL = "https://myvard.fangwl591021.workers.dev"
LIFF_ID = "1660923784-EcoH8aMs"
LIFF_URL = "https://liff.line.me/1660923784-EcoH8aMs"
WASABI_BUCKET = "tonyuse"
WASABI_ENDPOINT = "https://s3.us-west-1.wasabisys.com"
WASABI_REGION = "us-west-1"
